Issue #334
codership/documentation pull request #341
Opened 2022-02-16 13:46 UTC by kirjaamo

Progress reporting documented.

2022-02-16 13:58 UTC, kirjaamo commented
Or do these reporting methods belong to the sender's calling conventions?

2022-02-17 09:45 UTC, byte reviewed
for scriptable-sst.rst, i am not sure if this is actually doable. can you ask alexey?

for sst-physical.rst, this is ok, but have you noticed on line 130 it is spelt CLuster instead of Cluster? Please fix the capital L too

2022-02-23 16:52 UTC, ayurchen requested changes
Changes are needed, see inline comments

2022-02-23 16:52 UTC, ayurchen commented on galeracluster/source/documentation/scriptable-sst.rst
> +   Progress reporting is also enabled for the ``clone`` SST method.
This is a correct statement, but I'm not sure it belongs in the list of SST script parameters.

2022-02-23 16:52 UTC, ayurchen commented on galeracluster/source/documentation/scriptable-sst.rst
> +   ``--total N`` This progress reporting parameter indicates the new SST stage and reports the estimated total work.
This is not an SST script parameter, just like "complete". This is optional script output. For example, the script output on DONOR over the period of SST may look like:
```
flush tables
total 534
continue
complete 122
complete 340
complete 610
total 23
complete 20
done
```
Here we had two phases, one estimated 543 units of work length, another 23. First phase estimation was too small and we ended up doing a bit more. Second phase estimation may have been correct, but it was over before the full progress could be reported. Both `total` and `complete` messages are optional. In  the absence of those, we conclude that progress cannot be evaluated and just wait for `done` that unequivocally indicates that SST is finished.

The script outputs those control messages to standard output from where they are read by the parent mysqld process.

2022-02-23 16:52 UTC, ayurchen commented on galeracluster/source/documentation/scriptable-sst.rst
> +   ``--complete N`` This progress reporting parameter reports the work completed so far.
Same as above. These are not script parameters, these are script feedback to the caller.

2024-08-21 11:40 UTC, kirjaamo commented
@byte I could not resolve one conflict, so I created a new branch for it and made a pull request a minute ago.

Your comments for _scriptable-sst.rst_ are implemented in the original branch.

I hope this hassle does not complicate your life too much

2024-08-21 23:54 UTC, byte approved these changes
ok

2024-08-21 23:55 UTC, merged