Issue #363
codership/documentation pull request #365
Opened 2022-12-08 15:56 UTC by kirjaamo

Test run

2022-12-09 07:32 UTC, kirjaamo commented
@byte Can you check, please?

2022-12-12 13:20 UTC, byte requested changes
The copyright notice should follow the other percona styled documentation, and after i review that i will approve

2022-12-16 07:37 UTC, kirjaamo commented
@byte Copyright statement added

2022-12-19 21:04 UTC, byte approved these changes
ok to push

2022-12-19 21:05 UTC, merged